// import { env } from '@/env.mjs';

export const siteConfig = {
  name: 'Srisamrakshan',
  title: 'Srisamrakshan | Full-Stack developer',
  email: 'rakshan864@gmail.com',
  description:
        "I'm Srisamrakshan, a MERN stack dev skilled in React,Node.js & MongoDB.I craft-platform apps using Electron.",
  keywords: [
    'Srisamrakshan',
    'Full-Stack developer',
    'Indian developer',
    'Portfolio',
    'Software engineer',
    'Web developer',
    'Full-Stack',
    'Full-Stack development',
    'Software development',
    'Software engineer',
    'Programming',
    'Coding',
    'JavaScript',
    'TypeScript',
    'Node.js',
    'Express.js',
    'MongoDB',
    'PostgreSQL',
    'SQL',
    'HTML',
    'CSS',
    'Tailwind CSS',
    'Bootstrap',
    'React',
    'Next.js',
    'Web development',
    'Front-end',
    'UI/UX',
    'Responsive design',
    'Portfolio',
    'Projects',
    'Website',
    'Web applications',
    'Developer',
    'Code',
    'Programming',
    'Tech enthusiast',
  ],
  url: 'https://imsam.vercel.app',
  links: {
    github: 'https://github.com/Samrakshan-Prog',
    linkedin: 'https://www.linkedin.com/in/srisamrakshan/',
    instagram: 'https://www.instagram.com/_sam_jf',
  },
};
